// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://whatsrb.com/api/v1' | (string & {});
};

export type BusinessAccount = {
    id?: string;
    waba_id?: string;
    business_name?: string;
    phone_number_id?: string;
    phone_number?: string;
    display_name?: string;
    status?: string;
    quality_rating?: string;
    connected?: boolean;
    meta_token_expires_at?: string;
    created_at?: string;
    updated_at?: string;
};

export type BusinessMessage = {
    id?: string;
    direction?: 'outbound';
    to?: string;
    message_type?: 'text' | 'template' | 'image' | 'video' | 'audio' | 'document';
    content?: string;
    status?: 'queued' | 'sent' | 'delivered' | 'read' | 'failed';
    wamid?: string;
    error_message?: string;
    sent_at?: string;
    delivered_at?: string;
    read_at?: string;
    created_at?: string;
};

export type Template = {
    id?: string;
    meta_template_id?: string;
    name?: string;
    category?: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION';
    status?: 'approved' | 'pending' | 'rejected';
    language?: string;
    header_type?: string;
    components?: {
        [key: string]: unknown;
    };
    variable_examples?: {
        [key: string]: unknown;
    };
    rejection_reason?: string;
    created_at?: string;
    updated_at?: string;
};

export type Session = {
    id?: string;
    name?: string;
    status?: 'connecting' | 'qr_pending' | 'connected' | 'disconnected';
    status_reason?: string;
    phone_number?: string;
    qr_code?: string;
    connected?: boolean;
    last_connected_at?: string;
    created_at?: string;
    updated_at?: string;
};

export type SessionMessage = {
    id?: string;
    direction?: 'outbound';
    to?: string;
    message_type?: string;
    content?: string;
    status?: 'queued' | 'sent' | 'delivered' | 'read' | 'failed';
    whatsapp_message_id?: string;
    sent_at?: string;
    delivered_at?: string;
    read_at?: string;
    created_at?: string;
};

export type WebhookEndpoint = {
    id?: number;
    url?: string;
    events?: Array<string>;
    active?: boolean;
    created_at?: string;
    updated_at?: string;
};

export type Error = {
    error?: string;
    details?: unknown;
    upgrade_url?: string;
};

export type ResourceId = string;

export type GetBusinessAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/business_accounts';
};

export type GetBusinessAccountsErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
};

export type GetBusinessAccountsError = GetBusinessAccountsErrors[keyof GetBusinessAccountsErrors];

export type GetBusinessAccountsResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<BusinessAccount>;
        meta?: {
            total?: number;
            plan_limit?: number;
        };
    };
};

export type GetBusinessAccountsResponse = GetBusinessAccountsResponses[keyof GetBusinessAccountsResponses];

export type PostBusinessAccountsData = {
    body: {
        business_account: {
            /**
             * WhatsApp Business Account ID
             */
            waba_id?: string;
            /**
             * Meta phone number ID
             */
            phone_number_id?: string;
            business_name?: string;
            display_name?: string;
            phone_number?: string;
            /**
             * Meta access token
             */
            meta_access_token?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/business_accounts';
};

export type PostBusinessAccountsErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Plan limit reached
     */
    403: Error;
    /**
     * Validation failed
     */
    422: Error;
};

export type PostBusinessAccountsError = PostBusinessAccountsErrors[keyof PostBusinessAccountsErrors];

export type PostBusinessAccountsResponses = {
    /**
     * Created
     */
    201: {
        data?: BusinessAccount;
    };
};

export type PostBusinessAccountsResponse = PostBusinessAccountsResponses[keyof PostBusinessAccountsResponses];

export type PostBusinessAccountsConnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/business_accounts/connect';
};

export type PostBusinessAccountsConnectErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Plan limit reached
     */
    403: Error;
};

export type PostBusinessAccountsConnectError = PostBusinessAccountsConnectErrors[keyof PostBusinessAccountsConnectErrors];

export type PostBusinessAccountsConnectResponses = {
    /**
     * Created
     */
    201: {
        data?: {
            id?: string;
            url?: string;
            status?: 'pending';
            expires_at?: string;
        };
    };
};

export type PostBusinessAccountsConnectResponse = PostBusinessAccountsConnectResponses[keyof PostBusinessAccountsConnectResponses];

export type DeleteBusinessAccountsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/business_accounts/{id}';
};

export type DeleteBusinessAccountsByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteBusinessAccountsByIdError = DeleteBusinessAccountsByIdErrors[keyof DeleteBusinessAccountsByIdErrors];

export type DeleteBusinessAccountsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBusinessAccountsByIdResponse = DeleteBusinessAccountsByIdResponses[keyof DeleteBusinessAccountsByIdResponses];

export type GetBusinessAccountsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/business_accounts/{id}';
};

export type GetBusinessAccountsByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetBusinessAccountsByIdError = GetBusinessAccountsByIdErrors[keyof GetBusinessAccountsByIdErrors];

export type GetBusinessAccountsByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: BusinessAccount;
    };
};

export type GetBusinessAccountsByIdResponse = GetBusinessAccountsByIdResponses[keyof GetBusinessAccountsByIdResponses];

export type GetBusinessAccountsByBusinessAccountIdMessagesData = {
    body?: never;
    path: {
        /**
         * Business account ID
         */
        business_account_id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/messages';
};

export type GetBusinessAccountsByBusinessAccountIdMessagesErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetBusinessAccountsByBusinessAccountIdMessagesError = GetBusinessAccountsByBusinessAccountIdMessagesErrors[keyof GetBusinessAccountsByBusinessAccountIdMessagesErrors];

export type GetBusinessAccountsByBusinessAccountIdMessagesResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<BusinessMessage>;
        meta?: {
            total?: number;
        };
    };
};

export type GetBusinessAccountsByBusinessAccountIdMessagesResponse = GetBusinessAccountsByBusinessAccountIdMessagesResponses[keyof GetBusinessAccountsByBusinessAccountIdMessagesResponses];

export type PostBusinessAccountsByBusinessAccountIdMessagesData = {
    body: {
        message: {
            /**
             * Recipient phone number in E.164 format
             */
            to: string;
            message_type: 'text' | 'template' | 'image' | 'video' | 'audio' | 'document';
            /**
             * Message text (required for `message_type=text`)
             */
            content?: string;
            /**
             * Template name (required for `message_type=template`)
             */
            template_name?: string;
            /**
             * Template language code
             */
            template_language?: string;
        };
    };
    path: {
        /**
         * Business account ID
         */
        business_account_id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/messages';
};

export type PostBusinessAccountsByBusinessAccountIdMessagesErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Account not connected
     */
    409: Error;
    /**
     * Validation failed
     */
    422: Error;
    /**
     * Daily quota or rate limit exceeded
     */
    429: Error;
    /**
     * Meta API error
     */
    502: Error;
};

export type PostBusinessAccountsByBusinessAccountIdMessagesError = PostBusinessAccountsByBusinessAccountIdMessagesErrors[keyof PostBusinessAccountsByBusinessAccountIdMessagesErrors];

export type PostBusinessAccountsByBusinessAccountIdMessagesResponses = {
    /**
     * Sent
     */
    201: {
        data?: BusinessMessage;
    };
};

export type PostBusinessAccountsByBusinessAccountIdMessagesResponse = PostBusinessAccountsByBusinessAccountIdMessagesResponses[keyof PostBusinessAccountsByBusinessAccountIdMessagesResponses];

export type GetBusinessAccountsByBusinessAccountIdMessagesByIdData = {
    body?: never;
    path: {
        business_account_id: string;
        id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/messages/{id}';
};

export type GetBusinessAccountsByBusinessAccountIdMessagesByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetBusinessAccountsByBusinessAccountIdMessagesByIdError = GetBusinessAccountsByBusinessAccountIdMessagesByIdErrors[keyof GetBusinessAccountsByBusinessAccountIdMessagesByIdErrors];

export type GetBusinessAccountsByBusinessAccountIdMessagesByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: BusinessMessage;
    };
};

export type GetBusinessAccountsByBusinessAccountIdMessagesByIdResponse = GetBusinessAccountsByBusinessAccountIdMessagesByIdResponses[keyof GetBusinessAccountsByBusinessAccountIdMessagesByIdResponses];

export type GetBusinessAccountsByBusinessAccountIdTemplatesData = {
    body?: never;
    path: {
        business_account_id: string;
    };
    query?: {
        status?: 'approved' | 'pending' | 'rejected';
        category?: string;
    };
    url: '/business_accounts/{business_account_id}/templates';
};

export type GetBusinessAccountsByBusinessAccountIdTemplatesErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
};

export type GetBusinessAccountsByBusinessAccountIdTemplatesError = GetBusinessAccountsByBusinessAccountIdTemplatesErrors[keyof GetBusinessAccountsByBusinessAccountIdTemplatesErrors];

export type GetBusinessAccountsByBusinessAccountIdTemplatesResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<Template>;
        meta?: {
            total?: number;
        };
    };
};

export type GetBusinessAccountsByBusinessAccountIdTemplatesResponse = GetBusinessAccountsByBusinessAccountIdTemplatesResponses[keyof GetBusinessAccountsByBusinessAccountIdTemplatesResponses];

export type PostBusinessAccountsByBusinessAccountIdTemplatesData = {
    body: {
        template: {
            name: string;
            category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION';
            language: string;
            header_type?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'DOCUMENT';
            /**
             * Template components (header, body, footer, buttons)
             */
            components?: {
                [key: string]: unknown;
            };
            /**
             * Example values for template variables
             */
            variable_examples?: {
                [key: string]: unknown;
            };
        };
    };
    path: {
        business_account_id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/templates';
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Validation failed
     */
    422: Error;
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesError = PostBusinessAccountsByBusinessAccountIdTemplatesErrors[keyof PostBusinessAccountsByBusinessAccountIdTemplatesErrors];

export type PostBusinessAccountsByBusinessAccountIdTemplatesResponses = {
    /**
     * Created
     */
    201: {
        data?: Template;
    };
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesResponse = PostBusinessAccountsByBusinessAccountIdTemplatesResponses[keyof PostBusinessAccountsByBusinessAccountIdTemplatesResponses];

export type PostBusinessAccountsByBusinessAccountIdTemplatesSyncData = {
    body?: never;
    path: {
        business_account_id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/templates/sync';
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesSyncErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesSyncError = PostBusinessAccountsByBusinessAccountIdTemplatesSyncErrors[keyof PostBusinessAccountsByBusinessAccountIdTemplatesSyncErrors];

export type PostBusinessAccountsByBusinessAccountIdTemplatesSyncResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<Template>;
        meta?: {
            total?: number;
        };
    };
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesSyncResponse = PostBusinessAccountsByBusinessAccountIdTemplatesSyncResponses[keyof PostBusinessAccountsByBusinessAccountIdTemplatesSyncResponses];

export type DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdData = {
    body?: never;
    path: {
        business_account_id: string;
        id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/templates/{id}';
};

export type DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdError = DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdErrors[keyof DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdErrors];

export type DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdResponse = DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdResponses[keyof DeleteBusinessAccountsByBusinessAccountIdTemplatesByIdResponses];

export type GetBusinessAccountsByBusinessAccountIdTemplatesByIdData = {
    body?: never;
    path: {
        business_account_id: string;
        id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/templates/{id}';
};

export type GetBusinessAccountsByBusinessAccountIdTemplatesByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetBusinessAccountsByBusinessAccountIdTemplatesByIdError = GetBusinessAccountsByBusinessAccountIdTemplatesByIdErrors[keyof GetBusinessAccountsByBusinessAccountIdTemplatesByIdErrors];

export type GetBusinessAccountsByBusinessAccountIdTemplatesByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: Template;
    };
};

export type GetBusinessAccountsByBusinessAccountIdTemplatesByIdResponse = GetBusinessAccountsByBusinessAccountIdTemplatesByIdResponses[keyof GetBusinessAccountsByBusinessAccountIdTemplatesByIdResponses];

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneData = {
    body?: never;
    path: {
        business_account_id: string;
        id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/templates/{id}/clone';
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneError = PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneErrors[keyof PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneErrors];

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneResponses = {
    /**
     * Created
     */
    201: {
        data?: Template;
    };
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneResponse = PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneResponses[keyof PostBusinessAccountsByBusinessAccountIdTemplatesByIdCloneResponses];

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestData = {
    body: {
        to: string;
    };
    path: {
        business_account_id: string;
        id: string;
    };
    query?: never;
    url: '/business_accounts/{business_account_id}/templates/{id}/send_test';
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestError = PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestErrors[keyof PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestErrors];

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestResponses = {
    /**
     * Sent
     */
    201: {
        data?: BusinessMessage;
    };
};

export type PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestResponse = PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestResponses[keyof PostBusinessAccountsByBusinessAccountIdTemplatesByIdSendTestResponses];

export type GetSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sessions';
};

export type GetSessionsErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
};

export type GetSessionsError = GetSessionsErrors[keyof GetSessionsErrors];

export type GetSessionsResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<Session>;
        meta?: {
            total?: number;
            plan_limit?: number;
        };
    };
};

export type GetSessionsResponse = GetSessionsResponses[keyof GetSessionsResponses];

export type PostSessionsData = {
    body: {
        session: {
            name: string;
        };
    };
    path?: never;
    query?: never;
    url: '/sessions';
};

export type PostSessionsErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Plan limit reached
     */
    403: Error;
    /**
     * Validation failed
     */
    422: Error;
};

export type PostSessionsError = PostSessionsErrors[keyof PostSessionsErrors];

export type PostSessionsResponses = {
    /**
     * Created
     */
    201: {
        data?: Session;
    };
};

export type PostSessionsResponse = PostSessionsResponses[keyof PostSessionsResponses];

export type DeleteSessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type DeleteSessionsByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteSessionsByIdError = DeleteSessionsByIdErrors[keyof DeleteSessionsByIdErrors];

export type DeleteSessionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSessionsByIdResponse = DeleteSessionsByIdResponses[keyof DeleteSessionsByIdResponses];

export type GetSessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type GetSessionsByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetSessionsByIdError = GetSessionsByIdErrors[keyof GetSessionsByIdErrors];

export type GetSessionsByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: Session;
    };
};

export type GetSessionsByIdResponse = GetSessionsByIdResponses[keyof GetSessionsByIdResponses];

export type PatchSessionsByIdData = {
    body: {
        status: 'connecting' | 'qr_pending' | 'connected' | 'disconnected';
        phone_number?: string;
        /**
         * Base64-encoded QR code
         */
        qr_code?: string;
        status_reason?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type PatchSessionsByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Validation failed
     */
    422: Error;
};

export type PatchSessionsByIdError = PatchSessionsByIdErrors[keyof PatchSessionsByIdErrors];

export type PatchSessionsByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: Session;
    };
};

export type PatchSessionsByIdResponse = PatchSessionsByIdResponses[keyof PatchSessionsByIdResponses];

export type GetSessionsBySessionIdMessagesData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/sessions/{session_id}/messages';
};

export type GetSessionsBySessionIdMessagesErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetSessionsBySessionIdMessagesError = GetSessionsBySessionIdMessagesErrors[keyof GetSessionsBySessionIdMessagesErrors];

export type GetSessionsBySessionIdMessagesResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<SessionMessage>;
        meta?: {
            total?: number;
        };
    };
};

export type GetSessionsBySessionIdMessagesResponse = GetSessionsBySessionIdMessagesResponses[keyof GetSessionsBySessionIdMessagesResponses];

export type PostSessionsBySessionIdMessagesData = {
    body: {
        message: {
            to: string;
            message_type: 'text';
            content: string;
        };
    };
    path: {
        session_id: string;
    };
    query?: never;
    url: '/sessions/{session_id}/messages';
};

export type PostSessionsBySessionIdMessagesErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Session not connected
     */
    409: Error;
    /**
     * Daily quota or rate limit exceeded
     */
    429: Error;
};

export type PostSessionsBySessionIdMessagesError = PostSessionsBySessionIdMessagesErrors[keyof PostSessionsBySessionIdMessagesErrors];

export type PostSessionsBySessionIdMessagesResponses = {
    /**
     * Sent
     */
    201: {
        data?: SessionMessage;
    };
};

export type PostSessionsBySessionIdMessagesResponse = PostSessionsBySessionIdMessagesResponses[keyof PostSessionsBySessionIdMessagesResponses];

export type GetSessionsBySessionIdMessagesByIdData = {
    body?: never;
    path: {
        session_id: string;
        id: string;
    };
    query?: never;
    url: '/sessions/{session_id}/messages/{id}';
};

export type GetSessionsBySessionIdMessagesByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetSessionsBySessionIdMessagesByIdError = GetSessionsBySessionIdMessagesByIdErrors[keyof GetSessionsBySessionIdMessagesByIdErrors];

export type GetSessionsBySessionIdMessagesByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: SessionMessage;
    };
};

export type GetSessionsBySessionIdMessagesByIdResponse = GetSessionsBySessionIdMessagesByIdResponses[keyof GetSessionsBySessionIdMessagesByIdResponses];

export type PatchSessionsBySessionIdMessagesByIdData = {
    body: {
        status: 'sent' | 'delivered' | 'read' | 'failed';
        whatsapp_message_id?: string;
        error?: string;
    };
    path: {
        session_id: string;
        id: string;
    };
    query?: never;
    url: '/sessions/{session_id}/messages/{id}';
};

export type PatchSessionsBySessionIdMessagesByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Validation failed
     */
    422: Error;
};

export type PatchSessionsBySessionIdMessagesByIdError = PatchSessionsBySessionIdMessagesByIdErrors[keyof PatchSessionsBySessionIdMessagesByIdErrors];

export type PatchSessionsBySessionIdMessagesByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: SessionMessage;
    };
};

export type PatchSessionsBySessionIdMessagesByIdResponse = PatchSessionsBySessionIdMessagesByIdResponses[keyof PatchSessionsBySessionIdMessagesByIdResponses];

export type GetWebhooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhooks';
};

export type GetWebhooksErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
};

export type GetWebhooksError = GetWebhooksErrors[keyof GetWebhooksErrors];

export type GetWebhooksResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<WebhookEndpoint>;
        meta?: {
            total?: number;
        };
    };
};

export type GetWebhooksResponse = GetWebhooksResponses[keyof GetWebhooksResponses];

export type PostWebhooksData = {
    body: {
        webhook: {
            url: string;
            active?: boolean;
            events?: Array<'message.received' | 'message.status' | 'message.failed' | 'session.connected' | 'session.disconnected' | 'session.failed' | 'quota.warning' | 'quota.exceeded'>;
        };
    };
    path?: never;
    query?: never;
    url: '/webhooks';
};

export type PostWebhooksErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Validation failed
     */
    422: Error;
};

export type PostWebhooksError = PostWebhooksErrors[keyof PostWebhooksErrors];

export type PostWebhooksResponses = {
    /**
     * Created
     */
    201: {
        data?: WebhookEndpoint & {
            /**
             * HMAC signing secret — only returned on creation
             */
            secret?: string;
        };
    };
};

export type PostWebhooksResponse = PostWebhooksResponses[keyof PostWebhooksResponses];

export type DeleteWebhooksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/webhooks/{id}';
};

export type DeleteWebhooksByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteWebhooksByIdError = DeleteWebhooksByIdErrors[keyof DeleteWebhooksByIdErrors];

export type DeleteWebhooksByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteWebhooksByIdResponse = DeleteWebhooksByIdResponses[keyof DeleteWebhooksByIdResponses];

export type GetWebhooksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/webhooks/{id}';
};

export type GetWebhooksByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetWebhooksByIdError = GetWebhooksByIdErrors[keyof GetWebhooksByIdErrors];

export type GetWebhooksByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: WebhookEndpoint;
    };
};

export type GetWebhooksByIdResponse = GetWebhooksByIdResponses[keyof GetWebhooksByIdResponses];

export type PatchWebhooksByIdData = {
    body?: {
        webhook?: {
            url?: string;
            active?: boolean;
            events?: Array<string>;
        };
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/webhooks/{id}';
};

export type PatchWebhooksByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type PatchWebhooksByIdError = PatchWebhooksByIdErrors[keyof PatchWebhooksByIdErrors];

export type PatchWebhooksByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: WebhookEndpoint;
    };
};

export type PatchWebhooksByIdResponse = PatchWebhooksByIdResponses[keyof PatchWebhooksByIdResponses];

export type GetUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/usage';
};

export type GetUsageErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
};

export type GetUsageError = GetUsageErrors[keyof GetUsageErrors];

export type GetUsageResponses = {
    /**
     * OK
     */
    200: {
        data?: {
            plan?: 'free' | 'pro' | 'scale';
            sessions?: {
                used?: number;
                limit?: number;
            };
            daily_business_messages?: {
                used?: number;
                limit?: number;
                remaining?: number;
            };
            daily_session_messages?: {
                used?: number;
                limit?: number;
                remaining?: number;
            };
            send_enabled?: boolean;
        };
    };
};

export type GetUsageResponse = GetUsageResponses[keyof GetUsageResponses];

export type GetUsageMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/usage/metrics';
};

export type GetUsageMetricsErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
};

export type GetUsageMetricsError = GetUsageMetricsErrors[keyof GetUsageMetricsErrors];

export type GetUsageMetricsResponses = {
    /**
     * OK
     */
    200: {
        data?: {
            sessions?: {
                total?: number;
                connected?: number;
                disconnect_rate_24h?: number;
            };
            messages?: {
                total_24h?: number;
                sent_24h?: number;
                failed_24h?: number;
                success_rate_24h?: number;
                avg_delivery_latency_ms?: number;
            };
        };
    };
};

export type GetUsageMetricsResponse = GetUsageMetricsResponses[keyof GetUsageMetricsResponses];

export type GetConnectsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/connects/{id}';
};

export type GetConnectsByIdErrors = {
    /**
     * Invalid or missing API key
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetConnectsByIdError = GetConnectsByIdErrors[keyof GetConnectsByIdErrors];

export type GetConnectsByIdResponses = {
    /**
     * OK
     */
    200: {
        data?: {
            id?: string;
            status?: 'pending' | 'completed' | 'failed' | 'expired';
            expires_at?: string;
            created_at?: string;
            /**
             * Only present when `status=completed`
             */
            account?: BusinessAccount;
            /**
             * Only present when `status=failed`
             */
            error?: string;
        };
    };
};

export type GetConnectsByIdResponse = GetConnectsByIdResponses[keyof GetConnectsByIdResponses];
